"""
Fixed top-N-by-dollar-volume backtest universe (configs/universe.yaml).

User-confirmed design decision (2026-07-28): the self-improve WFO loop and
the default backtest runs use a FIXED list of the top-N (default 20) most
liquid US names — ranked by trailing 60-day average dollar volume as of a
chosen snapshot date — instead of a per-day re-ranked universe. A fixed
list makes iterations comparable (parameter changes are the ONLY thing that
varies between loop runs) and keeps IB Gateway pacing manageable (20 names,
not 600).

Honesty caveat, stated everywhere the list is used: a universe ranked at
`as_of` and then applied to EARLIER dates carries mild survivorship flavor
(today's most liquid names were not necessarily 2018's). configs/universe.yaml
therefore records `computed_at` + ranking settings, every report labels the
universe with that snapshot date, and scripts/refresh_universe.py warns when
a selected symbol's history starts after the intended backtest start.

Look-ahead note: the ranking itself reuses
liquid_universe.top_by_trailing_dollar_volume (strictly-before-`as_of`
window), so the LIST construction has no look-ahead — the caveat above is
about applying one snapshot list across time, which is a deliberate,
documented trade-off, not an accident.

`top_n` / `lookback_days` are DATA-WINDOW / UNIVERSE-CONSTRUCTION settings,
not statistically-fit strategy parameters (same classification as
liquid_universe.py's lookback/top_k) — they do not count against the Chan
Ch.3 5-parameter budget.
"""
from __future__ import annotations

import hashlib
from datetime import datetime
from pathlib import Path

import pandas as pd
import yaml

from .liquid_universe import top_by_trailing_dollar_volume

UNIVERSE_CONFIG_PATH = Path("configs/universe.yaml")
DEFAULT_TOP_N = 20
DEFAULT_LOOKBACK_DAYS = 60


def select_fixed_top_n(
    pool: list[str],
    price_panel: pd.DataFrame,
    as_of: datetime,
    top_n: int = DEFAULT_TOP_N,
    lookback_days: int = DEFAULT_LOOKBACK_DAYS,
) -> list[str]:
    """Rank `pool` by mean(close * volume) over the `lookback_days` trading
    days strictly before `as_of` and return the top `top_n`, sorted for
    stable YAML diffs. `price_panel` is a (date, code)-MultiIndex frame with
    close+volume (price_cache / build_price_panel contract)."""
    ranked = top_by_trailing_dollar_volume(
        candidates=pool,
        price_panel=price_panel,
        as_of=as_of,
        lookback_days=lookback_days,
        top_k=top_n,
    )
    return sorted(ranked)


def save_universe_config(
    symbols: list[str],
    as_of: datetime,
    lookback_days: int,
    source_pool_label: str,
    path: str | Path = UNIVERSE_CONFIG_PATH,
) -> None:
    doc = {
        "fixed_universe": {
            "symbols": sorted(s.upper() for s in symbols),
            "top_n": len(symbols),
            "ranking_metric": f"trailing_{lookback_days}d_avg_dollar_volume",
            "computed_at": str(pd.Timestamp(as_of).date()),
            "source_pool": source_pool_label,
        }
    }
    header = (
        "# Fixed backtest universe — generated by scripts/refresh_universe.py.\n"
        "# Do not hand-edit the symbol list; re-run the script to refresh.\n"
        "# See python/data/fixed_universe.py for the survivorship caveat that\n"
        "# comes with applying one liquidity snapshot across historical dates.\n"
    )
    Path(path).write_text(header + yaml.safe_dump(doc, sort_keys=False), encoding="utf-8")


def load_universe_config(path: str | Path = UNIVERSE_CONFIG_PATH) -> dict:
    """Return the `fixed_universe` block ({symbols, top_n, ranking_metric,
    computed_at, source_pool}). Raises with a run-the-script hint when the
    file is missing so a fresh clone gets an actionable error."""
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(
            f"{path} not found — run `python scripts/refresh_universe.py` to build the "
            "fixed backtest universe first"
        )
    with open(path, encoding="utf-8") as f:
        doc = yaml.safe_load(f) or {}
    block = doc.get("fixed_universe")
    if not block or not block.get("symbols"):
        raise ValueError(f"{path} has no fixed_universe.symbols — re-run scripts/refresh_universe.py")
    return block


def universe_fingerprint(universe_cfg: dict) -> str:
    """Short stable hash of (symbols, computed_at) — stored in promotion
    records so a parameter promoted under one universe is never mistaken
    for one validated under another."""
    payload = ",".join(sorted(universe_cfg["symbols"])) + "|" + str(universe_cfg.get("computed_at", ""))
    return hashlib.sha1(payload.encode("utf-8")).hexdigest()[:12]
