"""
The narrative half of backtests/reports/orb_vwap_rescue_report.md.

Kept in its own module (rather than as one enormous string literal inside
scripts/_merge_orb_rescue_report.py) purely for readability — the merge
script owns loading the checkpoints and rendering the numeric tables; this
module owns the prose those tables sit inside. Every number that appears in
a sentence here is interpolated from the same checkpoint dicts the tables
are built from, so the prose cannot silently drift from the data.
"""
from __future__ import annotations

from datetime import datetime, timezone


def render(results, diag, n_dev, render_lever_table, render_gate_detail, pf_of):
    r = results  # shorthand
    hold = r.get("HOLDOUT_best")
    best = r.get("E2_r2")
    a0, a1 = r.get("A0_asshipped_full20"), r.get("A1_stopfix_full20")
    b1, b2 = r.get("B1_tight10"), r.get("B2_tight6")
    d3, c1 = r.get("D3_atr100"), r.get("C1_cap1")
    n_total = len(r)

    flat = r.get("F1_best_flat")
    lines: list[str] = [
        "# orb_vwap Cost-to-Edge Rescue — Report",
        "",
        f"Generated: {datetime.now(timezone.utc).isoformat()}",
        "",
        "> Report-only, same discipline as `intraday_backtest_report.md` /",
        "> `new_signals_report.md` / `slippage_calibration_report.md`: a GO below would be",
        "> evidence for a human to review, not an automatic promotion. No gate threshold in",
        "> `configs/goal.yaml` was changed, `auto_execute` stays `false` for every strategy,",
        "> and no params were written back into `configs/strategy.yaml` by this work (see",
        "> `python/backtest/promotion.py`'s `_FORBIDDEN_WRITE_KEYS`/human-in-the-loop path).",
        "",
        "## HEADLINE",
        "",
        f"**NO-GO.** {n_total} configurations were evaluated ({n_dev} on the development window,",
        "1 on the untouched final holdout). The four levers together lifted `orb_vwap`'s",
        f"cost-adjusted profit factor from **{pf_of(a0):.3f}** (as-shipped, 20 symbols) to",
        f"**{pf_of(best):.3f}** on the development window — the first `orb_vwap` configuration in this",
        "repo's history to reach breakeven under real calibrated per-symbol costs. It is still",
        "far short of the **1.3** required by `configs/goal.yaml`'s",
        "`intraday.min_cost_adjusted_profit_factor`, and it fails four of the seven gates.",
        "",
        "**The holdout is worse, not better.** Evaluated exactly once on the final two months",
        f"of 1-minute history ({hold['window']}), the frozen best configuration produced a",
        f"cost-adjusted profit factor of **{pf_of(hold):.3f}** — below even the as-shipped baseline, and",
        f"{pf_of(best) - pf_of(hold):.3f} below its own in-sample value — on {hold['full_window_metrics']['n_trades']:,} trades, with",
        f"net P&L of **${hold['full_window_metrics']['total_net_pnl']:,.0f}**. The in-sample improvement did not generalize.",
        "",
        "**Two findings matter more than the levers themselves:**",
        "",
        "1. **Part of `orb_vwap`'s apparent raw edge was a stop-side defect, not an edge.**",
        "   The gap-trap rule flipped the trade `direction` but not the stop assignment,",
        "   leaving the stop on the FAVORABLE side of entry for every trap-faded trade —",
        "   which `intraday_engine._check_exit` then booked as an immediate *profitable*",
        f"   exit labelled `\"stop\"`. Correcting that (Lever 0 below, `A0`→`A1`) drops the",
        f"   full-window cost-adjusted PF from {pf_of(a0):.3f} to **{pf_of(a1):.3f}** and the mean OOS Sharpe from",
        f"   {a0['oos_sharpe_mean']:+.3f} to **{a1['oos_sharpe_mean']:+.3f}** on identical data, universe and costs. Scope note,",
        "   so this is not over-claimed: that measurement is on the development window under",
        "   calibrated costs. The often-quoted \"+1.407 mean OOS Sharpe\" is a FLAT-cost,",
        "   11-month figure that was produced with the defect present and was not re-measured",
        "   post-fix (its window overlaps this exercise's holdout, so it could not be). Given",
        "   the size of the effect where it WAS measured, that number should not be relied on.",
        "   Every lever row below is measured on the corrected signal and is therefore not",
        "   comparable to any previously published `orb_vwap` number.",
        "2. **The levers do work, in the direction the review predicted — they are just not",
        "   big enough.** All four together recovered",
        f"   {pf_of(best) - pf_of(a1):+.3f} of profit factor from the corrected baseline ({pf_of(a1):.3f} → {pf_of(best):.3f}).",
        f"   Reaching the 1.3 gate needs another {1.3 - pf_of(best):+.3f} — roughly 70% as much again as",
        "   the entire four-lever programme delivered, from levers that are already spent.",
        "",
        "## 1. What was tested, and why",
        "",
        "Per `backtests/reports/strategy_review_summary.md` §3.3, `orb_vwap` was the only",
        "signal in the system with a genuinely positive raw walk-forward pattern that failed",
        "purely on cost drag: 21,707 trades over 11 months across 20 symbols, cost-adjusted PF",
        "0.940 flat / 0.871 calibrated, Monte Carlo p5 Sharpe -4.263, 2x-slippage stress",
        "-$4.74M. Four levers were derived from that review's specific findings and tested",
        "**incrementally**, each on top of the current best, never as a combinatorial grid:",
        "",
        "| Lever | Hypothesis (from the review) | How it is implemented |",
        "|---|---|---|",
        "| 1. Tight-spread universe | Calibration §(d): trading broadly across all 20 symbols — half of them above the 2.0bps flat assumption — is the direct cause of the cost blowup. | Data-universe restriction in the runner, not a signal parameter. TIGHT10 = the 10 symbols with calibrated half-spread <= 1.89bps; TIGHT6 = the 6 at <= 1.00bps. |",
        "| 2. Entries-per-session cap | ~4-5 entries per symbol per day is implausible for a once-per-session opening-range event. | New `max_entries_per_session` param, enforced in `intraday_engine.run_symbol_day` (session-scoped state the per-bar signal deliberately does not carry). |",
        "| 3. ATR stop buffer | The raw opening-range extreme is a tight stop relative to ordinary 1-minute noise right after the break. | New `stop_atr_buffer_mult` param in `evaluate_orb_vwap`: stop = structural extreme -/+ k * ATR14. |",
        "| 4. Profit target | `target_price=None` caps reward but not risk — winners are cut by the time-stop/EOD flatten while losers hit a tight stop. | New `target_r_multiple` param: target = entry -/+ R * stop distance. |",
        "",
        "All three new parameters default to the pre-existing behavior (`null` / `0.0` /",
        "`null` in `configs/strategy.yaml`), so nothing about the shipped configuration",
        "changed. With them, `orb_vwap` has **5 free parameters** — exactly at",
        "`python/backtest/param_guard.py`'s `MAX_FREE_PARAMETERS` ceiling, not over it. The",
        "universe restriction is deliberately NOT one of them: it is an eligibility/data",
        "decision of the same kind as `xsection_mean_reversion`'s fixed universe, but see",
        "the overfitting section — it was still chosen by looking at results, and it is",
        "counted as a degree of freedom there.",
        "",
        "### Lever 0 — a correctness defect found while instrumenting the signal",
        "",
        "`scripts/_orb_vwap_diagnostics.py` (read-only, 20 symbols, 2025-08-01..2025-11-01,",
        "`or_minutes=5`) measured the three things the review asserted but never quantified:",
        "",
    ]

    if diag:
        ord_pnl = diag.get("pnl_by_entry_ordinal", {})
        lines += [
            f"- **Re-firing is real:** {diag['mean_fills_per_symbol_session']:.1f} fills per symbol per session on average across",
            f"  {diag['symbol_sessions']:,} symbol-sessions; only {diag['fills_per_session_histogram'].get('1', 0)} sessions took exactly one entry, while the",
            "  distribution runs all the way out to 22 entries in a single symbol-session.",
            "- **Only the first entry of a session makes money.** Net P&L by entry ordinal:",
            "",
            "| Entry ordinal | Trades | Total net P&L | Mean per trade |",
            "|---|---|---|---|",
        ]
        for k in sorted(ord_pnl, key=int):
            v = ord_pnl[k]
            label = f"{k}" if k != "6" else "6+"
            lines.append(f"| {label} | {v['n']:,} | ${v['total']:,.0f} | ${v['mean']:,.2f} |")
        lines += [
            "",
            f"- **The gap-trap stop is inverted.** {diag['raw_signals_with_stop_on_favorable_side']:,} of {diag['total_raw_signals_every_bar']:,} raw signals",
            f"  ({diag['raw_signals_with_stop_on_favorable_side_pct']:.1f}%) — every single trap-flagged one — carried a stop on the",
            f"  FAVORABLE side of the entry, and {diag['stop_exits_that_made_money']['n']:,} `\"stop\"`-labelled exits booked",
            f"  **+${diag['stop_exits_that_made_money']['total_pnl']:,.0f}** of profit as a result.",
            "",
        ]

    lines += [
        "That last item is the same class of defect `fvg_retest.py` documents and already",
        "fixed for its target price. It is corrected here structurally rather than as a new",
        "knob: the stop is placed at the more ADVERSE of {the opening-range extreme, the",
        "breakout bar's own extreme}, which is a no-op for an ordinary breakout and puts a",
        "trap fade's stop beyond the failed-breakout extreme. A side effect worth stating",
        "plainly: that makes a trap fade's structural stop only a few ticks wide, which is",
        "why Lever 3 (the ATR buffer) was tested BEFORE Lever 2 — the risk unit had to be",
        "settled before anything downstream could be read against it.",
        "",
        "**This fix also changes `orb_vwap_regime`,** which calls `evaluate_orb_vwap`",
        "unchanged. `backtests/reports/new_signals_report.md`'s and",
        "`slippage_calibration_report.md`'s `orb_vwap_regime` numbers no longer reproduce",
        "on current code. That signal's verdict was, and remains, NO-GO; it was not re-run",
        "here.",
        "",
        "## 2. Methodology",
        "",
        f"- **Development window:** {a0['window']} (7 WFO folds at `configs/goal.yaml`'s",
        "  `orb_vwap` cadence: is_days=90, oos_days=30, step_days=30).",
        f"- **Final holdout:** {hold['window']} — the last two months of available 1-minute",
        "  history. Not looked at, in any form, until the single best development",
        "  configuration was frozen; evaluated exactly once, and reported below whatever it",
        "  said.",
        "- **Costs:** calibrated per-symbol half-spreads from",
        "  `backtests/reports/calibrated_spreads.json` (real captured Futu L2 depth) for",
        "  every headline number, in both the main run and the mandatory 2x-slippage stress",
        "  re-run. No flat-2.0bps result is used for any verdict.",
        "- **No per-fold re-optimization.** Every configuration is a SINGLE candidate forced",
        "  across every fold (`param_grid=[candidate]`), the same `old_fixed`/`new`",
        "  discipline as `scripts/_calibration_validation.py` — so each table row is one",
        "  config evaluated consistently, and a marginal row cannot be explained by",
        "  cherry-picking across a grid.",
        "- **Gates:** read unmodified from `configs/goal.yaml` — `wfo.min_pass_folds_ratio`",
        "  0.60, `wfo.min_oos_sharpe` 0.5, `wfo.max_oos_drawdown` 0.25,",
        "  `monte_carlo.min_p5_sharpe` 0.0, `intraday.min_trades_per_oos_fold` 100,",
        "  `intraday.min_cost_adjusted_profit_factor` 1.3, and a mandatory 2x-slippage",
        "  stress re-run that must stay net-positive.",
        "- **Durability:** `scripts/_orb_vwap_rescue.py` checkpoints every configuration to",
        "  `backtests/reports/_orb_rescue/` and disk-memoizes every individual",
        "  `backtest_fn(start, end, params)` call to `backtests/reports/_orb_rescue_cache/`",
        "  (atomic temp-file rename), so an interruption loses at most one in-flight fold.",
        "",
        "## 3. Lever-by-lever results (development window, calibrated per-symbol costs)",
        "",
    ]
    lines += render_lever_table(r)
    lines += [
        "",
        "Config column key: `cap` = `max_entries_per_session`, `atr` = `stop_atr_buffer_mult`,",
        "`R` = `target_r_multiple`; `or=5` and the VWAP side filter are the established",
        "candidate params from `slippage_calibration_report.md` and were never re-searched.",
        "",
        "### Reading the table",
        "",
        f"- **Lever 0 (`A0`→`A1`), the correctness fix, costs {pf_of(a1) - pf_of(a0):+.3f} PF.** This is not a lever,",
        "  it is the removal of a fake profit source. Everything below starts from",
        f"  PF {pf_of(a1):.3f}, not {pf_of(a0):.3f}.",
        f"- **Lever 1 (universe) is worth {pf_of(b1) - pf_of(a1):+.3f} PF at TIGHT10 and {pf_of(b2) - pf_of(a1):+.3f} at TIGHT6.** The",
        "  calibration report's §(d) diagnosis was correct: cutting the ten wide-spread names",
        "  is the single largest lever of the four. TIGHT6 scores better",
        f"  ({pf_of(b2):.3f} vs {pf_of(b1):.3f}) but leaves much less headroom on",
        "  `min_trades_per_oos_fold`; TIGHT10 was carried forward for that reason, and the",
        "  choice is revisited in the overfitting section.",
        f"- **Lever 3 (stop buffer) is worth {pf_of(d3) - pf_of(b1):+.3f} PF and is NOT monotone.** 0.25/0.50/1.00 ATR",
        f"  improve steadily to {pf_of(d3):.3f}, then 2.00 ATR gives it back ({pf_of(r['D4_atr200']):.3f}). That",
        "  interior optimum is the useful evidence: the gain is a genuine \"the stop was",
        "  inside the noise\" effect, not the trivial artifact of widening the stop until it",
        "  never triggers (which would have kept improving).",
        f"- **Lever 2 (entry cap) is worth {pf_of(c1) - pf_of(d3):+.3f} PF, the second-largest effect.** Capping at the",
        f"  first qualifying break per session cuts trades from {d3['full_window_metrics']['n_trades']:,} to",
        f"  {c1['full_window_metrics']['n_trades']:,} and takes PF from {pf_of(d3):.3f} to {pf_of(c1):.3f}, exactly as the",
        "  entry-ordinal diagnostic predicted. `cap=2` keeps more trades and a higher WFO",
        f"  pass ratio ({r['C2_cap2']['wfo_pass_ratio']:.0%} vs {c1['wfo_pass_ratio']:.0%}) but a worse PF ({pf_of(r['C2_cap2']):.3f}); PF is the",
        "  binding gate, so `cap=1` was carried forward.",
        f"- **Lever 4 (target) is worth {pf_of(best) - pf_of(c1):+.3f} PF at 2R.** 1R is actively harmful",
        f"  ({pf_of(r['E1_r1']):.3f}, below the no-target {pf_of(c1):.3f}) — a 1:1 target on this pattern cuts",
        "  winners before they pay for the losers, the same failure mode",
        f"  `fvg_retest` has. 2R ({pf_of(r['E2_r2']):.3f}) and 3R ({pf_of(r['E3_r3']):.3f}) are statistically",
        "  indistinguishable.",
        "",
        "### Selection rule for the frozen configuration",
        "",
        "Declared before the E row was run: primary metric = full-window cost-adjusted",
        "profit factor (the binding gate); tie-break when |ΔPF| < 0.01 = mean OOS Sharpe.",
        f"`E3_r3` wins on PF by {pf_of(r['E3_r3']) - pf_of(r['E2_r2']):.3f} — inside the tie-break band — and `E2_r2` wins the",
        f"tie-break on mean OOS Sharpe ({r['E2_r2']['oos_sharpe_mean']:+.3f} vs {r['E3_r3']['oos_sharpe_mean']:+.3f}), so the frozen configuration is:",
        "",
        f"```\n{_frozen_block(best)}\n```",
        "",
        "5 free parameters, exactly at the Chan Ch.3 ceiling.",
        "",
        "### Gate detail for the best development configuration",
        "",
    ]
    lines += render_gate_detail(best, f"`E2_r2` — development window ({best['window']}), calibrated costs")
    lines += [
        "None of the four failures is marginal: cost-adjusted PF needs 1.3 and no single",
        f"OOS fold reached it (best fold {max(best['fold_oos_profit_factors']):.2f}); Monte Carlo p5 Sharpe needs >= 0.0 and",
        f"is {best['mc_p5_sharpe']:+.3f}; the 2x-slippage stress must stay net-positive and is",
        f"${best['stress_metrics']['total_net_pnl']:,.0f}; the WFO pass ratio is {best['wfo_pass_ratio']:.0%} against a 0.60 bar.",
        f"Only `min_trades_per_oos_fold` and `oos_drawdown_within_limit` pass comfortably",
        f"(fold trade counts {min(best['fold_oos_trades'])}-{max(best['fold_oos_trades'])} against a 100 minimum).",
        "",
        "### Secondary context: the same configuration under the old flat 2.0bps assumption",
        "",
        "Every verdict above uses calibrated per-symbol spreads. For reference only, the",
        f"frozen configuration re-run at the flat 2.0bps assumption (`F1_best_flat`) scores",
        f"PF **{pf_of(flat):.3f}** (vs {pf_of(best):.3f} calibrated), mean OOS Sharpe {flat['oos_sharpe_mean']:+.3f}, Monte Carlo p5",
        f"{flat['mc_p5_sharpe']:+.3f}, 2x-stress ${flat['stress_metrics']['total_net_pnl']:,.0f} — also NO-GO.",
        "",
        "Note the sign: for THIS universe the flat assumption is now the *pessimistic* one,",
        "the reverse of `slippage_calibration_report.md` §(d)'s finding for the full 20",
        "symbols. That is direct mechanical confirmation that Lever 1 did what it was",
        "supposed to do — every symbol in TIGHT10 has a real calibrated half-spread below",
        "2.0bps, so restricting to them genuinely lowers the cost the strategy pays.",
        "",
        "It also puts a rough ceiling on how much more the cost side has left to give.",
        "TIGHT10's mean calibrated half-spread is ~1.02bps, so this pair of runs measures",
        f"what ~0.98bps per leg is worth: {pf_of(best) - pf_of(flat):+.3f} of profit factor. Removing the remaining",
        "~1.02bps entirely — a free-execution fantasy, no spread at all — would buy roughly",
        f"the same again, landing near PF {pf_of(best) + (pf_of(best) - pf_of(flat)):.2f}. Even adding back the commission and",
        "impact terms, a zero-cost version of this configuration does not plausibly reach",
        "1.3. That is a crude linear extrapolation from two points and should be read as an",
        "order-of-magnitude check, not a measurement — but it points the same way as",
        "everything else: after the four levers, the shortfall is a shortage of edge, not a",
        "surplus of cost, and no further cost engineering closes it.",
        "",
        "## 4. Final holdout — evaluated exactly once",
        "",
        f"Window `{hold['window']}` ({hold['n_symbols']} symbols, calibrated per-symbol costs),",
        "params frozen from the development phase, no re-optimization of any kind. Two",
        "months is shorter than a single is_days=90 + oos_days=30 WFO fold, so there is no",
        "honest per-fold pass ratio to compute; it is evaluated as one out-of-sample window",
        "and the gates that ARE well-defined on a single window are checked.",
        "",
        "| Metric | Development (in-sample) | **Final holdout** |",
        "|---|---|---|",
        f"| Cost-adjusted profit factor | {pf_of(best):.3f} | **{pf_of(hold):.3f}** |",
        f"| Total net P&L | ${best['full_window_metrics']['total_net_pnl']:,.0f} | **${hold['full_window_metrics']['total_net_pnl']:,.0f}** |",
        f"| Full-window Sharpe ratio | {best['full_window_metrics']['sharpe_ratio']:+.3f} | **{hold['full_window_metrics']['sharpe_ratio']:+.3f}** |",
        f"| Mean OOS Sharpe (WFO) | {best['oos_sharpe_mean']:+.3f} | n/a (window < 1 fold) |",
        f"| Monte Carlo p5 Sharpe | {best['mc_p5_sharpe']:+.3f} | **{hold['mc_p5_sharpe']:+.3f}** |",
        f"| 2x-slippage stress net P&L | ${best['stress_metrics']['total_net_pnl']:,.0f} | **${hold['stress_metrics']['total_net_pnl']:,.0f}** |",
        f"| Trades | {best['full_window_metrics']['n_trades']:,} | **{hold['full_window_metrics']['n_trades']:,}** |",
        f"| Max drawdown | — | {hold['full_window_metrics']['max_drawdown']:.1%} |",
        "",
    ]
    lines += render_gate_detail(hold, f"Final holdout ({hold['window']}), calibrated costs")
    lines += [
        "**The holdout contradicts the in-sample result, and it should be reported as the",
        "more informative of the two.** The configuration's whole claim was that four levers",
        f"had lifted cost-adjusted PF from {pf_of(a0):.3f} to {pf_of(best):.3f}. On data that played no part in",
        f"choosing those levers it delivers {pf_of(hold):.3f} — worse than the as-shipped baseline the",
        f"rescue started from, and {pf_of(best) - pf_of(hold):.3f} below its own in-sample value. The honest reading",
        "is that most of the in-sample gain was selection, not edge; that is exactly what a",
        "reserved holdout exists to detect, and it detected it.",
        "",
        "Two caveats, in both directions. Against the holdout's severity: 42 trading days /",
        f"{hold['full_window_metrics']['n_trades']:,} trades is a small sample, one bad month could dominate it, and its",
        "Monte Carlo p5 is computed from only 42 daily observations (which is why it is so",
        "much more negative than the development window's). In the holdout's favour: it is",
        "not marginal. A configuration that genuinely needed PF 1.3 to be tradeable",
        "delivered 0.713, and no plausible sampling correction bridges that.",
        "",
        "## 5. Overfitting-risk assessment",
        "",
        "Stated plainly, because this is the part of the exercise most easily fooled:",
        "",
        f"1. **This is at least the fourth round of hypothesis testing on the same 20 symbols",
        "   and the same ~12 months of 1-minute bars** (`intraday_backtest_report.md`,",
        "   `new_signals_report.md`'s 6-candidate grid searches, `slippage_calibration_report.md`,",
        "   and now this). The prior rounds' data-snooping cost is already sunk into any",
        "   in-sample number produced here, and cannot be undone by this round's discipline.",
        f"2. **{n_dev} development configurations is a modest search, but it is not zero.** With",
        "   ~7 folds and PF differences of 0.03-0.05 between adjacent rows, the difference",
        "   between `E2` and `E3`, or between `cap=1` and `cap=2`, is inside the noise. The",
        "   selection rule was declared in advance and the tie-break was needed — which is",
        "   itself a signal that the top of the search is flat.",
        "3. **The universe restriction is a hidden degree of freedom.** TIGHT10 vs TIGHT6 was",
        "   chosen by looking at results, which makes the effective parameter count 6, not 5,",
        "   for data-snooping purposes even though `param_guard.py` counts 5. In this one",
        f"   case the freedom was not exercised in the flattering direction: TIGHT6 scored",
        f"   BETTER in-sample ({pf_of(b2):.3f} vs {pf_of(b1):.3f}) and was still passed over, for",
        "   `min_trades_per_oos_fold` headroom. That does not make the degree of freedom",
        "   disappear — it just means this instance of it did not inflate the headline.",
        "4. **Sample-size rule of thumb is violated by a wide margin.** 5 free parameters",
        "   wants ~1,260 trading days by Chan's 252-per-parameter rule; the development",
        f"   window has {a0['sample_size_check']['total_trading_days']} and the holdout {hold['sample_size_check']['total_trading_days']}. Intraday bars carry more independent",
        "   observations per day than the rule assumes, so this is an informational flag",
        "   rather than a hard failure — but it is a flag in the same direction as everything",
        "   else here.",
        "5. **The one thing NOT at risk of overfitting is the verdict.** Every configuration",
        "   tested, including the best one, fails multiple gates by wide margins under",
        "   calibrated costs, and the holdout is worse than the starting point. Overfitting",
        "   risk matters when a result looks good; here it only means the true numbers are",
        "   probably a little worse than the in-sample table already says.",
        "",
        "## 6. Conclusion",
        "",
        "`orb_vwap` remains **NO-GO** under calibrated per-symbol costs, and the case against",
        "it is now stronger than it was before this investigation, not weaker:",
        "",
        "- Its headline raw edge was partly a stop-side defect. On corrected code the",
        f"  as-shipped configuration's mean OOS Sharpe is {a1['oos_sharpe_mean']:+.3f}, not {a0['oos_sharpe_mean']:+.3f}, and its",
        f"  cost-adjusted PF is {pf_of(a1):.3f}, not {pf_of(a0):.3f}.",
        "- All four levers pointed the right way and all four together reached only",
        f"  PF {pf_of(best):.3f} in-sample against a 1.3 requirement.",
        f"- The frozen configuration delivered PF {pf_of(hold):.3f} and ${hold['full_window_metrics']['total_net_pnl']:,.0f} on the untouched",
        "  holdout.",
        f"- After the levers, this is no longer a cost story: at the flat 2.0bps assumption —",
        f"  wider than every real spread in the chosen universe — it still only reaches",
        f"  PF {pf_of(flat):.3f}.",
        "",
        "The natural next question is whether an opening-range breakout has any tradeable",
        "edge on this universe at all once the trap artifact is removed, and that is a",
        "different (and much less promising) question than the cost-drag one this",
        "investigation was commissioned to answer. Nothing here supports spending more",
        "compute on `orb_vwap` parameter space.",
        "",
        "The lever code stays in the repo as explicit, defaulted-off, documented options with",
        "test coverage, because the levers are reusable and the measurements are worth",
        "keeping. Nothing is promoted, `configs/strategy.yaml`'s `orb_vwap` block keeps its",
        "original behavior and `auto_execute: false`, and no gate was touched.",
        "",
        "## Appendix — artifacts",
        "",
        "- `scripts/_orb_vwap_diagnostics.py` -> `backtests/reports/_orb_vwap_diagnostics.json`",
        "- `scripts/_orb_vwap_rescue.py` -> `backtests/reports/_orb_rescue/<config_id>.json`",
        "  (one checkpoint per configuration, including the full gate dict and per-fold OOS",
        "  Sharpe/trade-count/profit-factor series)",
        "- `scripts/_merge_orb_rescue_report.py` -> this file and its `.json` sibling",
        "- run logs: `backtests/logs/orb_rescue/*.log`",
        "- memoized per-fold backtests: `backtests/reports/_orb_rescue_cache/`",
        "",
    ]
    return lines


def _frozen_block(best: dict) -> str:
    p = best["params"]
    return (
        "universe            : AAPL GOOGL NVDA MSFT PLTR INTC META AVGO AMD QCOM  (tight-spread 10)\n"
        f"or_minutes              : {p['or_minutes']}\n"
        f"vwap_side_filter        : {str(p['vwap_side_filter']).lower()}\n"
        f"max_entries_per_session : {p['max_entries_per_session']}\n"
        f"stop_atr_buffer_mult    : {p['stop_atr_buffer_mult']:g}\n"
        f"target_r_multiple       : {p['target_r_multiple']:g}"
    )
